export const FETCH_ALL = "FETCH_ALL"
export const FETCH_CARS = "FETCH_CARS"
export const GET_CAR = "GET_CAR"
export const  RE_GET_CAR = " RE_GET_CAR"
export const CLEAR_CAR = "CLEAR_CAR"
export const FETCH_COMMENTS = "FETCH_COMMENTS"
export const FETCH_IMAGE = "GET_IMAGE"
export const CREATE_COMMUNITY = "CREATE_COMMUNITY"
export const CREATE_RULES = "CREATE_RULES"
export const EDIT_RULES = "EDIT_RULES"
export const CREATE_IMAGE = "CREATE_IMAGE"
export const CREATE_CARS = "CREATE_CARS"
export const CREATE_COMMENTS = "CREATE_COMMENTS"
export const DELETE = "DELETE"
export const UPDATE = "UPDATE" 
export const FETCH_STICKERS = "FETCH_STICKERS"
export const UPDATE_STICKER = "UPDATE_STICKER"
export const DELETE_STICKER = "DELETE_STICKER"
export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"
export const LOGOUT2 = "LOGOUT2"
export const CREATE_VIOLATION = "CREATE_VIOLATIOM"
export const GET_VIOLATION = "GET_VIOLATION"
export const DELETE_VIOLATION = "DELETE_VIOLATION"
export const VIOLATION_LIST = "VIOLATION_LIST"
export const GET_SAFELIST = "GET_SAFELIST"
export const UPDATE_SAFELIST= "UPDATE_SAFELIST"
export const DELETE_VIOLATION_AT = "DELETE_VIOLATION_AT"
export const REFETCHCARIMAGE = "REFETCHCARIMAGE"
export const DELETECOM = "DELETECOM"


// carIndex
export const WEEKLY_CARS = "WEEKLY_CARS"
export const GET_CAR_AMOUNT = "GET_CAR_AMOUNT"
export const GET_TOTAL_VIOLATIONS = "GET_TOTAL_VIOLATIONS"

// Index Total
export const INDEX_TOTAL = "INDEX_TOTAL"

// Car Profile
export const GET_PROFILE = 'GET_PROFILE'
export const PHOTOID ="PHOTOID"
export const CREATE_CARIMAGE = "CREATE_CARIMAGE"
export const SHOW_IMAGE = "SHOW_IMAGE"

// Auth
export const USERACCESS = "USERACCESS"
export const ADMINACCESS= "ADMINACCESS"

//ViolationList
export const GETVIOLATIONLIST = "GETVIOLATIONLIST"
export const CREATEVIOLATIONLIST = "CREATEVIOLATIONLIST"
export const DELETEVIOLATIONLIST = "DELETEVIOLATIONLIST"
export const SWITCHAUTOTOW = "SWITCHAUTOTOW"

export const CARRYLP = "CARRYLP"
export const CLEAR_LP = "CLEAR_LP"